name: Release on Tag

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set tag name and zip filename
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "ZIP_NAME=mqtt-integration-${GITHUB_REF#refs/tags/}.zip" >> $GITHUB_ENV

      - name: Create folder_name and copy files
        run: |
          mkdir mqtt-integration
          rsync -av --exclude='.*' --exclude='mqtt-integration' --exclude='README.md' ./ mqtt-integration/

      - name: Zip mqtt-integration
        run: |
          zip -r $ZIP_NAME mqtt-integration

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
